CinemaRevs/urls.py
from django.contrib import admin
from django.urls import path
from CinemaRevs import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='Index'),
    path('contacto/', views.contact, name='Contact'),
    path('about/', views.about, name='About'),
    path('reviews/', views.reviews, name='Reviews'),
    path('search/', views.search, name='Search'),
    path('editprofile/', views.editProfile, name='EditProfile'),
    path('reviews_list/', views.ReviewsListView.as_view(), name='ReviewsList'),
    path('reviews_detail/<pk>', views.ReviewsDetailView.as_view(), name='ReviewsDetail'),
    path('reviews_delete/<pk>', views.ReviewsDeleteView.as_view(), name='ReviewsDelete'),
    path('reviews_create/', views.ReviewsCreateView.as_view(), name='ReviewsCreate'),
    path('reviews_update/<pk>', views.ReviewsUpdateView.as_view(), name='ReviewsUpdate'),
    path('signup/', views.SignUpView.as_view(), name='SignUp'),
    path('login/', views.AdminLoginView.as_view(), name='Login'),
    path('logout/', views.AdminLogoutView.as_view(), name='Logout'),
    path('profile/<pk>', views.ProfileView.as_view(), name='Profile'),
    path('addavatar/', views.addAvatar, name='Avatar'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinalMorel/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('CinemaRevs.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
]

CinemaRevs/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from tinymce.models import HTMLField

# Create your models here.
class Reviews(models.Model):
    title = models.CharField(max_length=40)
    film = models.CharField(max_length=40)
    body = HTMLField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='images/reviews', null=True, blank=True)
    date = models.DateField(default=now)

    def __str__(self):
        return f'Title: {self.title}, Film: {self.film}, Body: {self.body}, Author: {self.author}, Date: {self.date}'

class Contact(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=90)
    message = models.CharField(max_length=250)

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/avatars', null=True, blank=True)

    def __str__(self):
        return f'User: {self.user}, Image: {self.image}'

CinemaRevs/forms.py
from django import forms
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateContact(forms.Form):
    name = forms.CharField(max_length=40)
    email = forms.EmailField(max_length=90)
    message = forms.CharField(max_length=250, widget=forms.Textarea(attrs={'class': 'form-control-file'}))

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
            ]
        help_text = {k: '' for k in fields}

class UserEditForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            ]
        help_text = {k: '' for k in fields}

class AvatarForm(forms.Form):
    image = forms.ImageField()

CinemaRevs/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import *
from .models import *
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

# Create your views here.

def index(request):

    # if request.user.is_authenticated():    

    #     images = Avatar.objects.filter(user=request.user.id)

    #     return render(request, 'index.html', {'url': images[0].image.url})

    # else:
        return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    
    if request.method == "POST":

        contact_form = CreateContact(request.POST)

        if contact_form.is_valid():

            formulario_contacto = contact_form.cleaned_data

            contacto = Contact(name=formulario_contacto["name"], email=formulario_contacto["email"], message=formulario_contacto["message"])

            contacto.save()

            return render(request, "CinemaRevs/templates/index.html")
    else:
        contact_form = CreateContact()
        
    return render(request, "contact.html", {"contact_form": contact_form})

def reviews(request):

    review_list = Reviews.objects.all()

    context = {'reviews_list': review_list}

    return render(request, 'reviews.html', context=context)

def search(request):
     if request.GET.get('film', False):
        film = request.GET['film']

        found = Reviews.objects.filter(film__icontains=film)

        return render(request, "search.html", {"found":found})
     else:
        respuesta = "No results found"
    
     return render(request, 'search.html', {'respuesta': respuesta})


def editProfile(request):

    user = request.user

    if request.method == 'POST':
        editprofile_form = UserEditForm(request.POST)

        if editprofile_form.is_valid():

            information = editprofile_form.cleaned_data

            user.username = information['username']
            user.email = information['email']
            user.password1 = information['password']
            user.password2 = information['password2']
            user.save()

            return render(request, 'index.html')

    else:

        editprofile_form = UserEditForm(initial={'username': user.username, 'email': user.email})

    return render(request, 'Profile/editprofile.html', {'form': editprofile_form, 'user': user})

def addAvatar(request):
    if request.method == 'POST':

        avatar_form = AvatarForm(request.POST, request.FILES)
        
        if avatar_form.is_valid():

            currentUser = User.objects.get(username=request.user)
            avatar = Avatar(user=currentUser, image=avatar_form.cleaned_data['image'])
            avatar.save()
            return render(request, 'index.html')

    else:

        avatar_form = AvatarForm()

        return render(request, 'Profile/addAvatar.html', {'avatar_form': avatar_form})

class ProfileView(DetailView):
    model = User
    template_name = 'Profile/profile.html'

# class UserList(ListView):
#     model = User
#     template_name = 'userlist.html'

class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('Index')
    template_name = 'register.html'

class AdminLoginView(LoginView):
    template_name = 'login.html'

class AdminLogoutView(LogoutView):
    template_name = 'logout.html'

class ReviewsListView(ListView):
    model = Reviews
    template_name ='Reviews/reviews_list.html'

class ReviewsDetailView(DetailView):
    model = Reviews
    template_name ='Reviews/reviews_detail.html'

class ReviewsDeleteView(DeleteView):
    model = Reviews
    success_url = '/reviews_list'
    template_name = 'Reviews/reviews_delete.html'

class ReviewsCreateView(LoginRequiredMixin, CreateView):
    model = Reviews
    success_url = reverse_lazy('ReviewsList')
    template_name = 'Reviews/reviews_create.html'
    fields = ['title', 'body', 'film', 'image']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self, **kwargs):         
        if  kwargs != None:
            return reverse_lazy('ReviewsList')
        else:
            return reverse_lazy('ReviewsList')

class ReviewsUpdateView(UpdateView):
    model = Reviews
    success_url = '/reviews_list'
    template_name = 'Reviews/reviews_update.html'
    fields = ['title', 'body', 'film', 'image']

CinemaRevs/templates/Profile/addAvatar.html
{% extends 'Profile/editprofile.html' %}

{% load static %}

{% block codigoDinamico %}

<div class="container" style="margin-top: 120px;">
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{avatar_form.as_p}}
        <input type="submit" value="Save Avatar">
    </form>
</div>

{% endblock %}}

CinemaRevs/templates/Profile/editAvatar.html
{% extends 'Profile/editprofile.html' %}

{% load static %}

{% block codigoDinamico %}

<div class="container" style="margin-top: 120px;">
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{avatar_form.as_p}}
        <input type="submit" value="Save Avatar">
    </form>
</div>

{% endblock %}}

CinemaRevs/templates/Profile/editprofile.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}

<div class="container"">
    <h1>Edit profile</h1>
    <h3 class="mt-3">{{ user.username }}</h3>
    
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <!-- {{form.as_p}} -->
        <div class="container mt-3 d-flex align-items-start flex-column">
            {{ form.non_field_errors }}
            <div class="d-flex align-items-start flex-column">
                {{form.username.errors}}
                <label for='{{form.username.id_for_label}}'>Username</label>
                {{form.username}}
            </div>
            <div class="d-flex align-items-start flex-column">
                {{form.first_name.errors}}
                <label for='{{form.first_name.id_for_label}}'>First Name</label>
                {{form.first_name}}
            </div>
            <div class="d-flex align-items-start flex-column">
                {{form.last_name.errors}}
                <label for='{{form.last_name.id_for_label}}'>Last Name</label>
                {{form.last_name}}
            </div>
            <div class="d-flex align-items-start flex-column">
                {{form.email.errors}}
                <label for='{{form.email.id_for_label}}'>Email</label>
                {{form.email}}
            </div>
            <div class="d-flex align-items-start flex-column">
                {{form.password1.errors}}
                <label for='{{form.password1.id_for_label}}'>Password</label>
                {{form.password1}}
            </div>
            <div class="d-flex align-items-start flex-column">
                {% if form.password2.errors %}
                <ul class="mt-2 text-muted" style="list-style: none;">
                    {% for error in form.password2.errors %}
                    <li>{{ error|escape }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <label for='{{form.password2.id_for_label}}'>Confirm Password</label>
                {{form.password2}}
            </div>
        </div>
        <div class="container my-4">
            <button class="btn btn-primary rounded-pill" id="submitButton" type="submit">Submit</button>
            <a href={% url 'ReviewsList' %}><button class="btn btn-secondary rounded-pill" type="button" >Cancel</button></a>
            {% if true %}
            <a href={% url 'Avatar' %}><button class="btn btn-primary rounded-pill" type="button">Edit Avatar</button></a>
            {% endif %}
        </div>
    </form>
</div>


{% endblock codigoDinamico %}

CinemaRevs/templates/Profile/profile.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}

<div class="container" style="margin-top: 100px;">
    <h2>{{user.username}}</h2>
    <ul>
        <li>First Name: {{user.first_name}}</li>
        <li>Last Name: {{user.last_name}}</li>
        <li>{{user.email}}</li>
    </ul>
    
    <a href={% url 'EditProfile' %}><button class="btn btn-primary btn-sm mb-2 rounded-pill">Edit Profile</button></a>
</div>

{% endblock %}

CinemaRevs/templates/Reviews/reviews_create.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}

<div class="container mb-5" style="margin-top: 120px;">
    <h1 class="mb-4">Add a Review</h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
    
        {{form.as_p}}
        <button class="btn btn-primary rounded-pill" id="submitButton" type="submit">Submit</button>
        <a href={% url 'ReviewsList' %}>
            <button class="btn btn-secondary rounded-pill" type="button" >Cancel</button>
        </a>
    </form>
</div>

{% endblock codigoDinamico %}

CinemaRevs/templates/Reviews/reviews_delete.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}
<div class="container mb-5" style="margin-top: 100px;">
    <div class="col-md-4 mb-3">
        <h2>Confirm Delete</h2>
        <span>Review title: {{object.title}}</span>
    </div>
    
    <form method="post"> {% csrf_token %}
        <p>Are you sure you want to delete this review?</p>
        <button class="btn btn-primary rounded-pill" id="submitButton" type="submit">Confirm</button>
        <a href={% url 'ReviewsList' %}>
            <button class="btn btn-secondary rounded-pill" type="button">Cancel</button>
        </a>
    </form>

</div>

{% endblock codigoDinamico %}

CinemaRevs/templates/Reviews/reviews_detail.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}
<div class="d-flex flex-column align-items-center bg-gradient" style="margin-top: 50px;">
    <div style="height: 400px;">
        {% if reviews.image %}
        <img src='{{reviews.image.url}}' alt="..." height="400">
        {% else %}
        <img src='' alt="IMG" class="img-fluid rounded-start" alt="...">
        {% endif %}
    </div>
</div>
<div class="container my-4">
    <h1 class="text-center mb-5">{{reviews.title}}</h1>
    <p class="text-break">{{reviews.body}}</p>
</div>
<div class="container my-5 d-flex justify-content-center">
    <a href={% url 'ReviewsList' %}>
        <button class="btn btn-primary rounded-pill">Back  to Reviews</button>
    </a>
</div>

{% endblock codigoDinamico %}

CinemaRevs/templates/Reviews/reviews_list.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}

<div class="container d-flex align-items-center justify-content-between">
    <h1 class="h1" style="margin-top: 100px;">Reviews</h1>
    <button class="btn btn-primary" style="border-radius: 20px;">
        <a href="{% url 'ReviewsCreate' %}" style="color: white; text-decoration:none">Add a review</a>
    </button>
</div>
<div class="container mb-5">
    <div class="mt-5 row d-flex justify-content-evenly" id="portfolio">
        {% if object_list %}
        {%  for review in object_list  %}
                <div class="card mb-3 mx-2 col-md-4" style="max-width: 600px;">
                    <div class="row g-0">
                        {% if review.image %}
                        <div class="col-md-4">
                            <a href={% url 'ReviewsDetail' review.id %} style="color: black; text-decoration:none"><img src='{{review.image.url}}' class="img-fluid rounded-start" alt="..."></a>
                        </div>
                        {% else %}
                        <div class="col-md-4">
                            <a href={% url 'ReviewsDetail' review.id %} style="color: black; text-decoration:none"><img src='' alt="IMG" class="img-fluid rounded-start" alt="..."></a>
                        </div>
                        {% endif %}
                        <div class="col-md-8">
                                <a href={% url 'ReviewsDetail' review.id %} style="color: black; text-decoration:none">
                                <div class="card-body">
                                        <small class="text-muted">{{ review.film }}</small>
                                        <h3 class="card-title">{{ review.title }}</h3>
                                        <h6 class="card-subtitle">by: {{ review.author }}</h6>
                                        <p class="card-text"><small class="text-muted">{{ review.date }}</small></p>
                                </div>
                                {% if user.is_authenticated and user == review.author or user.is_superuser %}
                                <div class="container">
                                    <a href={% url 'ReviewsUpdate' review.id %}><button class="btn btn-success btn-sm mb-2 rounded-pill" style="color: white;">Edit</button></a>
                                    <a href={% url 'ReviewsDelete' review.id %}><button class="btn btn-secondary btn-sm mb-2 rounded-pill">Delete</button></a>
                                </div>
                                {% endif %}
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
            </div>
        <h3 class="my-5 text-muted">There are no reviews yet</h3>
        {% endif %}
    </div>


{% endblock codigoDinamico %}

CinemaRevs/templates/Reviews/reviews_update.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}

<style>
   #id_image{
    
   }
</style>

<div class="container mb-5" style="margin-top: 120px;">
    <h1 class="mb-4">Edit Review</h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
    
        {{form.as_p}}
        <button class="btn btn-primary rounded-pill" id="submitButton" type="submit">Submit</button>
        <a href={% url 'ReviewsList' %}>
            <button class="btn btn-secondary rounded-pill" type="button" >Cancel</button>
        </a>
    </form>
</div>

{% endblock codigoDinamico %}

CinemaRevs/templates/about.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}
<div style="height: 500px;overflow: hidden;" class="card text-bg-dark">
    <img  src="https://images.pexels.com/photos/3935026/pexels-photo-3935026.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="card-img"  alt="">
    <div class="d-flex align-items-center justify-content-center card-img-overlay">
    <h1 class="display-4 text-white card-title">About us</h1>
</div>
</div>
<div class="container" style="margin-top: 70px;">
    <figure class="text-center mb-5">
        <blockquote class="blockquote fs-3">
            <p>"When I wrote this code, only God and I understood what I did. Now only God knows."</p>
        </blockquote>
        <figcaption class="blockquote-footer">
            <cite title="Source Title">Anonymous</cite>
        </figcaption>
    </figure>
    <h1><strong>CinemaRevs</strong></h1>
    <div class="container">
        <p class="mt-5">CinemaRevs was created by Diego Morel, as the beggining of a journey in the realm of coding. This blog offered a wonderful chance to implement a wide range of concepts learned during the Coderhouse Python course. As a begginer back end coder, the lack of HTML and CSS knowledge was supported by his brother, Paulo Morel, also a Coderhouse student, by adding an aesthetic theme and structure to the blog.</p>
        <p>With the goal of further expanding our knowledge in programming languages and coding, we will continue looking for new information and experiences to reach the goal of making a profession out of it.</p>
        <div class="container" id="links">
            <a href="https://www.facebook.com/diego.morel.94/"><i class="bi bi-facebook fs-1 text-dark fs-2"></i></a>
            <a href="https://github.com/MorelDiego"><i class="bi bi-github fs-1 text-dark fs-2"></i></a>
        </div>
    </div>
</div>

{% endblock codigoDinamico %}

CinemaRevs/templates/contact.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}
<!-- Contact-->
    <div class="containerpx-4 px-lg-5" style="margin-top: 100px;">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="mt-0">Let's Get In Touch!</h2>
                <hr class="divider" />
                <p class="text-muted mb-2">Got any problems or suggestions to help us improve?</p>
                <p class="text-muted mb-5">Send us an email!</p>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <div class="col-lg-6">
                <form action="" id="contactForm" method="POST" > {% csrf_token %}
                    <table class="table g-3">
                        {{contact_form.as_table}}
                    </table> 
                    <!-- Submit Button-->
                    <div class="d-grid justify-content-center mt-3"><button class="btn btn-primary btn-xl" id="submitButton" type="submit">Submit</button></div>
                </form>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-4 text-center mb-5 mb-lg-0">
                <i class="bi-phone fs-2 mb-3 text-muted"></i>
                <div>+1 (555) 123-4567</div>
            </div>
        </div>
    </div>
{% endblock  %}

CinemaRevs/templates/crearcontacto.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}
<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="mt-0">Let's Get In Touch!</h2>
                <hr class="divider" />
                <p class="text-muted mb-5">Ready to start your next project with us? Send us a messages and we will get back to you as soon as possible!</p>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <div class="col-lg-6">
                <!-- * * * * * * * * * * * * * * *-->
                <!-- * * SB Forms Contact Form * *-->
                <!-- * * * * * * * * * * * * * * *-->
                <!-- This form is pre-integrated with SB Forms.-->
                <!-- To make this form functional, sign up at-->
                <!-- https://startbootstrap.com/solution/contact-forms-->
                <!-- to get an API token!-->
                <form action="" id="contactForm" method="POST" > {% csrf_token %}
                    <table>
                        {{formulario.as_table}}
                    </table> 
                    <!-- Submit Button-->
                    <div class="d-grid"><button class="btn btn-primary btn-xl" id="submitButton" type="submit">Submit</button></div>
                </form>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-4 text-center mb-5 mb-lg-0">
                <i class="bi-phone fs-2 mb-3 text-muted"></i>
                <div>+1 (555) 123-4567</div>
            </div>
        </div>
    </div>
</section>
{% endblock  %}

CinemaRevs/templates/login.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}

<div class="container" style="margin-top: 90px;">
    <h1 class="h1 title mb-4">Login</h1>
    <form action="" method="post">{% csrf_token %}
    
        {{form.as_p}}
    
        <button class="btn btn-primary btn-xl my-4" type="submit">Submit</button>
        
    </form>
</div>

{% endblock codigoDinamico %}

CinemaRevs/templates/register.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}

<div class="container" style="margin-top: 90px;">
    <h1 class="h1 title mb-4">Sign Up</h1>
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <!-- {{form.as_p}} -->
        <div class="container mt-3 d-flex align-items-start flex-column">
            {{ form.non_field_errors }}
            <div class="d-flex align-items-start flex-column">
                {{form.username.errors}}
                <label for='{{form.username.id_for_label}}'>Username</label>
                {{form.username}}
            </div>
            <div class="d-flex align-items-start flex-column">
                {{form.email.errors}}
                <label for='{{form.email.id_for_label}}'>Email</label>
                {{form.email}}
            </div>
            <div class="d-flex align-items-start flex-column">
                {{form.password1.errors}}
                <label for='{{form.password1.id_for_label}}'>Password</label>
                {{form.password1}}
            </div>
            <div class="d-flex align-items-start flex-column">
                {% if form.password2.errors %}
                <ul class="mt-2 text-muted" style="list-style: none;">
                    {% for error in form.password2.errors %}
                    <li>{{ error|escape }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <label for='{{form.password2.id_for_label}}'>Confirm Password</label>
                {{form.password2}}
            </div>
        </div>
        <div class="container my-4">
            <button class="btn btn-primary rounded-pill" id="submitButton" type="submit">Submit</button>
            <a href={% url 'ReviewsList' %}><button class="btn btn-secondary rounded-pill" type="button" >Cancel</button></a>
            {% if true %}
            <a href={% url 'Avatar' %}><button class="btn btn-primary rounded-pill" type="button">Edit Avatar</button></a>
            {% endif %}
        </div>
    </form>
</div>

{% endblock codigoDinamico %}

CinemaRevs/templates/search.html
{% extends 'index.html' %}

{% load static %}

{% block codigoDinamico %}
<div class="container" style="margin-top: 80px;">
  
  <h1>Search a Review</h1>
  <form style="margin-top: 40px;" action="" method="get">
      <input type="text" placeholder="Film title" name="film" id="film">
      <button class="btn btn-primary btn-sm rounded-pill" id="submitButton" type="submit">Search</button>
    </form>

{% if found %}
  <h4 class="mt-5">Results:</h4>
    {% for review in found %}
                <div class="card mb-3 mx-2 col-md-4" style="max-width: 600px;">
                    <div class="row g-0">
                        {% if review.image %}
                        <div class="col-md-4">
                            <a href={% url 'ReviewsDetail' review.id %} style="color: black; text-decoration:none"><img src='{{review.image.url}}' class="img-fluid rounded-start" alt="..."></a>
                        </div>
                        {% else %}
                        <div class="col-md-4">
                            <a href={% url 'ReviewsDetail' review.id %} style="color: black; text-decoration:none"><img src='' alt="IMG" class="img-fluid rounded-start" alt="..."></a>
                        </div>
                        {% endif %}
                        <div class="col-md-8">
                                <a href={% url 'ReviewsDetail' review.id %} style="color: black; text-decoration:none">
                                <div class="card-body">
                                        <small class="text-muted">{{ review.film }}</small>
                                        <h3 class="card-title">{{ review.title }}</h3>
                                        <h6 class="card-subtitle">by: {{ review.author }}</h6>
                                        <p class="card-text"><small class="text-muted">{{ review.date }}</small></p>
                                </div>
                                {% if user.is_authenticated and user == review.author or user.is_superuser %}
                                <div class="container">
                                    <a href={% url 'ReviewsUpdate' review.id %}><button class="btn btn-success btn-sm mb-2 rounded-pill" style="color: white;">Edit</button></a>
                                    <a href={% url 'ReviewsDelete' review.id %}><button class="btn btn-secondary btn-sm mb-2 rounded-pill">Delete</button></a>
                                </div>
                                {% endif %}
                            </a>
                        </div>
                    </div>
                </div>
    {% endfor %}

{% else %}
    <p style="margin-top: 30px;">{{respuesta}}</p>
{% endif %}

</div>

{% endblock  %}